const adjectives = [
  "Mysterious",
  "Whispering",
  "Shadow",
  "Ethereal",
  "Cosmic",
  "Digital",
  "Neon",
  "Phantom",
  "Crystal",
  "Quantum",
  "Stellar",
  "Void",
  "Echo",
  "Pulse",
  "Flux",
  "Nova",
  "Zen",
  "Luna",
  "Solar",
  "Galactic",
  "Cyber",
  "Vapor",
  "Dream",
  "Mirage",
  "Spectrum",
  "Prism",
  "Aurora",
  "Twilight",
  "Dawn",
  "Dusk",
  "Midnight",
  "Crimson",
  "Azure",
  "Emerald",
  "Golden",
  "Silver",
  "Platinum",
  "Obsidian",
  "Pearl",
  "Ruby",
  "Sapphire",
  "Amethyst",
  "Topaz",
  "Diamond",
];

const nouns = [
  "Traveler",
  "Wanderer",
  "Observer",
  "Dreamer",
  "Thinker",
  "Explorer",
  "Seeker",
  "Guardian",
  "Messenger",
  "Whisperer",
  "Listener",
  "Speaker",
  "Runner",
  "Walker",
  "Floater",
  "Dancer",
  "Singer",
  "Writer",
  "Reader",
  "Painter",
  "Sculptor",
  "Builder",
  "Creator",
  "Destroyer",
  "Warrior",
  "Mage",
  "Knight",
  "Rogue",
  "Wizard",
  "Sorcerer",
  "Monk",
  "Paladin",
  "Ranger",
  "Druid",
  "Bard",
  "Cleric",
  "Fighter",
  "Barbarian",
  "Warlock",
  "Artificer",
  "Alchemist",
  "Astronaut",
  "Pilot",
  "Captain",
  "Navigator",
  "Engineer",
  "Scientist",
  "Doctor",
  "Teacher",
  "Student",
  "Artist",
  "Musician",
  "Poet",
  "Philosopher",
  "Historian",
  "Archeologist",
];

const emojis = [
  "🌟",
  "✨",
  "💫",
  "⭐",
  "🌙",
  "☀️",
  "🌊",
  "🔥",
  "💧",
  "🌪️",
  "⚡",
  "🌈",
  "🎭",
  "🎪",
  "🎨",
  "🎭",
  "🎪",
  "🎯",
  "🎲",
  "🎮",
  "🎸",
  "🎹",
  "🎺",
  "🎻",
  "🥁",
  "🎤",
  "🎧",
  "🎵",
  "🦋",
  "🦅",
  "🦉",
  "🦊",
  "🐺",
  "🐱",
  "🐶",
  "🐼",
  "🐨",
  "🐯",
  "🦁",
  "🐸",
  "🐙",
  "🐬",
  "🚀",
  "🛸",
  "⚓",
  "🎪",
  "🎭",
  "🎨",
  "🎪",
  "🎭",
  "🎨",
  "🎪",
  "🎭",
  "🎨",
  "🎪",
  "🎭",
];

export function generateUsername(): string {
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  const emoji = emojis[Math.floor(Math.random() * emojis.length)];
  const number = Math.floor(Math.random() * 999) + 1;

  return `${adjective}${noun}${number}${emoji}`;
}

export function generateShortUsername(): string {
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  const emoji = emojis[Math.floor(Math.random() * emojis.length)];

  return `${adjective}${noun}${emoji}`;
}

export function generateColorFromUsername(username: string): string {
  const colors = [
    "bg-gradient-to-r from-purple-400 to-pink-400",
    "bg-gradient-to-r from-blue-400 to-cyan-400",
    "bg-gradient-to-r from-green-400 to-emerald-400",
    "bg-gradient-to-r from-yellow-400 to-orange-400",
    "bg-gradient-to-r from-red-400 to-pink-400",
    "bg-gradient-to-r from-indigo-400 to-purple-400",
    "bg-gradient-to-r from-teal-400 to-blue-400",
    "bg-gradient-to-r from-rose-400 to-red-400",
    "bg-gradient-to-r from-violet-400 to-purple-400",
    "bg-gradient-to-r from-amber-400 to-yellow-400",
    "bg-gradient-to-r from-lime-400 to-green-400",
    "bg-gradient-to-r from-sky-400 to-blue-400",
  ];

  const hash = username.split("").reduce((a, b) => {
    a = (a << 5) - a + b.charCodeAt(0);
    return a & a;
  }, 0);

  return colors[Math.abs(hash) % colors.length];
}
